name: Build and deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: Install v1.13.0
        run: |
          mkdir -p dist/v1.13.0
          npm install @gouvfr/dsfr@1.13.0
          cp -r node_modules/@gouvfr/dsfr/dist dist/v1.13.0/
          cp -r node_modules/@gouvfr/dsfr/example dist/v1.13.0/
          cp -r node_modules/@gouvfr/dsfr/storybook dist/v1.13.0/
          cp -r node_modules/@gouvfr/dsfr/doc dist/v1.13.0/
      - run: node build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'dist/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
